### ISSUE TITLE
Docs: Update Readme with code snippets examples for all the API methods 

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-ruby#28]
Right now, we have the methods documented in the readme. However, it's not comprehensive enough. It doesn't show examples of the parameters that should be passed in for each of the methods.

A very good comprehensive readme is that of the [Novu PHP SDK](https://github.com/novuhq/novu-php).

We need the Ruby Readme to be this comprehensive so that users can easily copy/paste code snippet into their codebase.

![Screenshot 2023-07-06 at 23 59 16](https://github.com/novuhq/novu-ruby/assets/2946769/7bbd775a-aae4-4e23-89fe-74613f9d6dbd)
![Screenshot 2023-07-06 at 23 59 29](https://github.com/novuhq/novu-ruby/assets/2946769/f467bf40-55fa-4896-b052-b9dedecd1280)

**Comment by Eazybright** [comment]
@unicodeveloper this should be fun!

**Comment by unicodeveloper** [comment]
Oh yes! Do you want to take on this one? @Eazybright

**Comment by Eazybright** [comment]
yes

**Comment by unicodeveloper** [comment]
Done.

**Comment by Eazybright** [comment]
@unicodeveloper PR has been open for this: https://github.com/novuhq/novu-ruby/pull/29

**Comment by unicodeveloper** [comment]
Thanks, I'll review it tomorrow @Eazybright

**Comment by unicodeveloper** [comment]
Done. So I'll close this now.
