### ISSUE TITLE
API: Add Tenants Feature - New Tenants API

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-ruby#32]
The tenants feature just became available this week in v19 on the UI and API.

This SDK needs to be updated to have this feature.

API reference: https://docs.novu.co/api-reference/tenants/

**Comment by unicodeveloper** [comment]
@Eazybright Do you want to take on this?

**Comment by unicodeveloper** [comment]
Alright, assigned to you @Eazybright

**Comment by Eazybright** [comment]
PR raised: https://github.com/novuhq/novu-ruby/pull/35
@unicodeveloper

**Comment by unicodeveloper** [comment]
Thanks, will take a look @Eazybright

**Comment by unicodeveloper** [comment]
Done!
