### ISSUE TITLE
Add Bulk Subscriber Creation Feature

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-ruby#33]
The bulk subscription feature just became available. This SDK needs to be updated to have this feature.

API reference: https://docs.novu.co/api-reference/subscribers/bulk-create-subscribers

**Comment by Eazybright** [comment]
@unicodeveloper would love to pick this up.

**Comment by unicodeveloper** [comment]
@Eazybright Assigning to you right away!

**Comment by Eazybright** [comment]
@unicodeveloper PR raised: https://github.com/novuhq/novu-ruby/pull/39
